"""initial schema

Revision ID: 02045f1ebc6a
Revises: 
Create Date: 2026-05-29 17:38:41.601191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02045f1ebc6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('resend_domain', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('current_step', sa.TEXT(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("current_step IS NULL OR current_step IN ('scraping', 'extracting', 'complete')", name='ck_ingestion_jobs_current_step'),
    sa.CheckConstraint("status IN ('running', 'done', 'failed')", name='ck_ingestion_jobs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_user_id', 'ingestion_jobs', ['user_id'], unique=False)
    op.create_table('product_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=False),
    sa.Column('one_liner', sa.TEXT(), nullable=True),
    sa.Column('target_customer', sa.TEXT(), nullable=True),
    sa.Column('pain_points', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('differentiators', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('case_studies', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('cta', sa.TEXT(), nullable=True),
    sa.Column('icp', sa.TEXT(), nullable=True),
    sa.Column('avoid_messaging', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_profiles_user_id', 'product_profiles', ['user_id'], unique=False)
    op.create_index('uq_product_profiles_user_id_active', 'product_profiles', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('outreach_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_profile_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.TEXT(), nullable=False),
    sa.Column('contact_name', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('current_step', sa.TEXT(), nullable=True),
    sa.Column('send_status', sa.TEXT(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('data_confidence', sa.TEXT(), nullable=True),
    sa.Column('email_subject', sa.TEXT(), nullable=True),
    sa.Column('email_draft', sa.TEXT(), nullable=True),
    sa.Column('linkedin_draft', sa.TEXT(), nullable=True),
    sa.Column('schedule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resend_message_id', sa.TEXT(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("current_step IS NULL OR current_step IN ('researching', 'personalizing', 'scheduling', 'complete')", name='ck_outreach_jobs_current_step'),
    sa.CheckConstraint("data_confidence IS NULL OR data_confidence IN ('low', 'medium', 'high')", name='ck_outreach_jobs_data_confidence'),
    sa.CheckConstraint("send_status IN ('draft', 'approved', 'sent', 'bounced', 'replied')", name='ck_outreach_jobs_send_status'),
    sa.CheckConstraint("status IN ('running', 'done', 'failed')", name='ck_outreach_jobs_status'),
    sa.ForeignKeyConstraint(['product_profile_id'], ['product_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outreach_jobs_status_running', 'outreach_jobs', ['status'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('ix_outreach_jobs_user_id', 'outreach_jobs', ['user_id'], unique=False)
    op.create_index('ix_outreach_jobs_user_id_created_at', 'outreach_jobs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outreach_jobs_user_id_created_at', table_name='outreach_jobs')
    op.drop_index('ix_outreach_jobs_user_id', table_name='outreach_jobs')
    op.drop_index('ix_outreach_jobs_status_running', table_name='outreach_jobs', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('outreach_jobs')
    op.drop_index('uq_product_profiles_user_id_active', table_name='product_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_product_profiles_user_id', table_name='product_profiles')
    op.drop_table('product_profiles')
    op.drop_index('ix_ingestion_jobs_user_id', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
